### ISSUE TITLE
highlight issue: '#' in a string causes rest of line to be treated as comment

### ISSUE THREAD

**Issue by colemickens** [LhKipp/tree-sitter-nu#10]
![screenshot-1694084397](https://github.com/LhKipp/tree-sitter-nu/assets/327028/0ef34c89-44bb-46ab-8e53-5c3e63d7ba88)

I believe those strings should be fully rendered as strings, rather than partially be rendered as if they were a comment, owing to the `#` usage.

If I change **a single line** to double quotes, things get even stranger:

![screenshot-1694084477](https://github.com/LhKipp/tree-sitter-nu/assets/327028/b3df8368-2f9d-4de6-9d31-f52fe620b083)

In fact, maybe this is linked to what I'm seeing in #9 ... I likely have this construct elsewhere in this file that might be confusing the parser? tree-sitter? etc.

**Comment by LhKipp** [comment]
Hi colemickens,

thanks for opening this issue. I can't create a minimal reproducible example while using the latest version of nvim-nu. Can you please either provide a minimal example or the whole script as _text_?

![image](https://github.com/LhKipp/tree-sitter-nu/assets/47630334/30612133-aa36-4a93-ae31-6fd6b4489639)

**Comment by colemickens** [comment]
I will definitely work on cutting this down, but my first crude attempt is showing all sorts of other interesting behavior as I remove various functions in pursuit of a minimal case.

FWIW, what I'm working with is helix-tip and this file: https://github.com/colemickens/nixcfg/blob/4f3fbe340dd25aafd45cc54007224914d84369d1/main.nu

If you grep for `def "main up"` you'll find the portion I used to file this bug, and if you start removing functions above it, you'll see some interesting behavior (note how `def` is highlighted as you go, etc).

I will keep this tab open with the hopes of cutting it down, but maybe you'll look and see something obvious too?

**Comment by colemickens** [comment]
Closing this. Helix uses nushell/tree-sitter-nu, not this repo. My mistake.
