### ISSUE TITLE
highlighting is slightly off with strings

### ISSUE THREAD

**Issue by amtoine** [LhKipp/tree-sitter-nu#3]
hello there :wave: :yum: 

i've been using `helix` for a few days now and really enjoy it :+1: 

**however, i have a slight issue with `nushell` scripts: see https://github.com/helix-editor/helix/issues/4162**

i'm new to all that grammar/syntax stuff, **do you have an idea to fix that?** :yum: 
**can i help in any way?** :relieved: 

cheers :tada:

**Comment by LhKipp** [comment]
Hi amtoine,

thanks for your feedback. I've added a fix for your problem at hand.

If you want to be of help next time, you can either open a PR with one of the following:
* a fix and a minimal test case
* a minimal failing test case

Cheers

**Comment by amtoine** [comment]
> thanks for your feedback. I've added a fix for your problem at hand.
> 
thanks a lot! :relieved: 
to be sure, is the fix 695e3ec794c74fb5a9bf4259128dff5fba6c0d71..eb95bdac3abd73ef47e53f19c63e74a31405ebd2 on the `main` branch or only a subset of commits? :yum: 

> If you want to be of help next time, you can either open a PR with one of the following:
> 
> * a fix and a minimal test case
> * a minimal failing test case
> 
not sure i understand how tree-sitter works for now, but got it :wink:

**Comment by amtoine** [comment]
i've been able to try the new revision and the bad highlighting is gone :star_struck: 
good job man :muscle:
