### ISSUE TITLE
Use queries in `nvim-treesitter` repository.

### ISSUE THREAD

**Issue by siph** [LhKipp/tree-sitter-nu#6]
While trying to figure out how to include this parser into my nix-based neovim configuration I quickly realized it would be easier to build a pr to put it into the official repository. Is it possible to use the queries from this repo in my pr? From my understanding `GPL3` code cannot be embedded into `Apache2` so I just wanted to check, if not I'll figure something else out.

**Comment by LhKipp** [comment]
Hi siph,

thanks for your question. I've thought about your request for long and came to the following conclusion: `nvim-treesitter` is a somewhat official neovim-plugin and therefore it providing correct syntax highlighting (etc.) or not, directly reflects back onto neovim. A tree-sitter grammar which was created for nushell versions ago, should for this reason not be included. Having this grammar/plugin in a separate low-star repo from a random guy on the internet, with a big warning, that the highlighting might not work, indicates the functionality of this grammar the best.
Additionally: Bringing this grammar into neovim-treesitter is not a one-time-thing. The queries have to be updated there, every time this repo changes. Issues in the neovim-treesitter list have to be responded and pointed to this repository etc... I don't feel like I want to take this extra work. I also don't feel like it is much of a burden for users, to install https://github.com/LhKipp/nvim-nu, if they want to use something half polished.

Thanks for your understanding.
