### ISSUE TITLE
Rookie Question: How do you get this working with Tree-Sitter?

### ISSUE THREAD

**Issue by dedguy21** [LhKipp/tree-sitter-nu#7]
I use neovim, it wasn't on the list of availalbe languages to be added via TSInstallInfo.  I know  i could alway down load this repo directly, but what are the next steps?

Thank you

**Comment by dedguy21** [comment]
oh, I found the neovim plugin. Closing issue as it is not relevant. Thank you.

**Comment by LhKipp** [comment]
For people wondering, which neovim plugin is meant: https://github.com/LhKipp/nvim-nu
