### ISSUE TITLE
highlight issue: random line breaks rest of syntax highlighting

### ISSUE THREAD

**Issue by colemickens** [LhKipp/tree-sitter-nu#9]
see:

![screenshot-1694084282](https://github.com/LhKipp/tree-sitter-nu/assets/327028/5cce977f-8f49-4f28-bdb1-77581c57bec2)

but if I remove the current line, 218, even though its valid syntax, then highlighting is fixed:

![screenshot-1694084330](https://github.com/LhKipp/tree-sitter-nu/assets/327028/1c9d1be0-7bd4-41d6-b8f3-808f40cdc50e)

**Comment by colemickens** [comment]
Here's a simpler case:

```
let DIR = $env.FILE_PWD
let cache = "nixpkgs-wayland"
```

this breaks. If you surround `$env.FILE_PWD` with parens, then it "fixes" syntax highlighting, but AFAIK, this is valid nushell without the parens.

**Comment by LhKipp** [comment]
Hi colemickens,

I can't reproduce the issue. Please see the image attached. 

![image](https://github.com/LhKipp/tree-sitter-nu/assets/47630334/8a73faec-fb25-4709-9f0c-0f2be262ef18)

**Comment by colemickens** [comment]
Maybe this is an issue with Helix, then?

![screenshot-1696111908](https://github.com/LhKipp/tree-sitter-nu/assets/327028/59cdae89-9400-40f5-bc3b-0f7f9d701c80)
![screenshot-1696111916](https://github.com/LhKipp/tree-sitter-nu/assets/327028/9fdee9c2-ff53-4254-833c-e7ebf404044e)

**Comment by colemickens** [comment]
This is very embarrassing. Helix is using this repo instead https://github.com/nushell/tree-sitter-nu/.

I will close both of my issues, so sorry about this.

**Comment by LhKipp** [comment]
👍🏻 

You don't need to feel embarrassed. Glad this got resolved ✌🏻
